import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { GetStaticProps } from 'next';
import { FC } from 'react';
import { Todo } from '../types';

export const getStaticProps: GetStaticProps = async () => {
  const { name } = await (await fetch('http://localhost:3000/api/hello')).json();
  const { todos } = await (await fetch('http://localhost:3000/api/todos')).json();
  return {
    props: {
      name,
      todos,
    },
  };
};

interface Props {
  name: string;
  todos: Todo[];
}

const Home: FC<Props> = ({ name, todos }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Todo List, {name}
        </h1>

        <h2>Your Todos &darr;</h2>

        {todos.map((todo) => (
          <div key={todo.id} className={styles.card}>
            <p>{todo.content}</p>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
